USE [master]
GO

/****** Object:  Database [testsForNAD]    Script Date: 2019-11-29 3:02:03 PM ******/
DROP DATABASE [testsForNAD]
GO

/****** Object:  Database [testsForNAD]    Script Date: 2019-11-29 3:02:03 PM ******/
CREATE DATABASE [testsForNAD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testsForNAD', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\testsForNAD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testsForNAD_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\testsForNAD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [testsForNAD] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testsForNAD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testsForNAD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testsForNAD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testsForNAD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testsForNAD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testsForNAD] SET ARITHABORT OFF 
GO

ALTER DATABASE [testsForNAD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testsForNAD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testsForNAD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testsForNAD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testsForNAD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testsForNAD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testsForNAD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testsForNAD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testsForNAD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testsForNAD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testsForNAD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testsForNAD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testsForNAD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testsForNAD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testsForNAD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testsForNAD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testsForNAD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testsForNAD] SET RECOVERY FULL 
GO

ALTER DATABASE [testsForNAD] SET  MULTI_USER 
GO

ALTER DATABASE [testsForNAD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testsForNAD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testsForNAD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testsForNAD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [testsForNAD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testsForNAD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [testsForNAD] SET  READ_WRITE 
GO

