// <auto-generated />
using System;
using System.Collections.Generic;
using Ef6CoreForPosgreSQL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NAD_IABRS.Migrations
{
    [DbContext(typeof(MyWebApiContext))]
    [Migration("20191110003413_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NAD_IABRS.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("bio");

                    b.Property<string>("fName")
                        .IsRequired();

                    b.Property<string>("lName")
                        .IsRequired();

                    b.Property<string>("mName");

                    b.HasKey("Id");

                    b.ToTable("authors");
                });

            modelBuilder.Entity("NAD_IABRS.Models.Book", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("isbn");

                    b.Property<int>("authorId");

                    b.Property<List<string>>("tagName")
                        .IsRequired();

                    b.Property<string>("title")
                        .IsRequired();

                    b.HasKey("Id", "isbn");

                    b.HasIndex("authorId");

                    b.ToTable("books");
                });

            modelBuilder.Entity("NAD_IABRS.Models.Tag", b =>
                {
                    b.Property<int>("tagName")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BookId");

                    b.Property<int?>("Bookisbn");

                    b.Property<string>("description")
                        .IsRequired();

                    b.HasKey("tagName");

                    b.HasIndex("BookId", "Bookisbn");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("NAD_IABRS.Models.Book", b =>
                {
                    b.HasOne("NAD_IABRS.Models.Author", "author")
                        .WithMany()
                        .HasForeignKey("authorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NAD_IABRS.Models.Tag", b =>
                {
                    b.HasOne("NAD_IABRS.Models.Book")
                        .WithMany("tags")
                        .HasForeignKey("BookId", "Bookisbn");
                });
#pragma warning restore 612, 618
        }
    }
}
